# Generated by Django 3.1.7 on 2021-04-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
