# Generated by Django 3.2 on 2021-05-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_blog_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
