# Generated by Django 3.2 on 2021-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_auto_20210508_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.IntegerField(),
        ),
    ]
